config/routes.rb
Rails.application.routes.draw do
  get 'oauths/oauth'

  get 'oauths/callback'

  root "home#index"

  resources :cards
  post "check_card" => "home#check_card"
  resources :users
  resources :user_sessions

  resources :decks do
    member do
      post :activate
    end
  end

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback" # for use with Github, Facebook
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

end

app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :user
  belongs_to :deck
  validates :original_text, :translated_text, :review_date, presence: true
  validates_with CompareStrings
  mount_uploader :avatar, AvatarUploader
  before_create do
    self.review_date = Time.now
  end

  def set_review_period
    case self.level
      when 0
        0
      when 1
        12.hours
      when 2
        3.days
      when 3
        1.weeks
      when 4
        2.weeks
      when 5
        1.month
    end
  end

  def increase_review_date(review)
    if review == 0
      self.level += 1 if self.level < 5
      update(review_date: self.review_date + self.set_review_period, attempt: 1, level: self.level)
    elsif self.attempt < 3
      update(attempt: self.attempt + 1)
    else
      self.level -= 1 if self.level > 1
      update(review_date: self.review_date - self.set_review_period, attempt: 1, level: self.level)
    end
  end

  def self.find_random_card
    # array = Card.check_date.map(&:id) --Вариант передачи параметра в метод .map
    # Card.check_date.pluck(:id)[rand(Card.check_date.pluck(:id).size)]
    where('review_date <= ?', Time.now).order("random()").limit(1)
  end

  def check_translate(usertext)
    Levenshtein.distance(usertext.downcase, original_text.downcase)
  end

  def self.send_mails
    Card.select(:user_id).distinct.where('review_date<?', Time.now).map do |i|
      CardMailer.send_expired_cards(User.find(i.user_id).email).deliver_now
    end
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :find_card, only: [:show, :edit, :update, :destroy]
  before_action :check_deck, only: [:new, :create, :edit, :update]

  def index
    @cards = current_user.cards
  end

  def show
  end

  def new
    @card = Card.new
  end

  def create
    @card = Card.create(get_card_params)

    if @card.save
      redirect_to cards_path
    else
      render "new"
    end
  end

  def edit
  end

  def update
    @card.update_attributes(get_card_params)

    if @card.errors.empty?
      redirect_to @card
    else
      render "edit"
    end
  end

  def destroy
    @card.destroy
    redirect_to cards_path
  end

  private

  def get_card_params
    params.require(:card).permit(:original_text, :translated_text, :review_date, :user_id, :avatar, :deck_id)
  end

  def find_card
    @card = Card.find(params[:id])
  end

  def check_deck
    @decks = current_user.decks
  end
end

app/views/cards/_form.html.erb
<div class="form-group">
  <%= f.label :deck_id, (t :deck), class: 'col-sm-2 control-label' %>
    <div class="col-sm-3">
        <%= f.select :deck_id, @decks.map { |r| [r.description, r.id] }, include_blank: false %>
    </div>
    <div class="col-sm-7">
    </div>
</div>

<div class="form-group">
  <%= f.label :original_text, (t :original_text), class: 'col-sm-2 control-label' %>
    <div class="col-sm-3">
      <%= f.input_field :original_text, as: :string, :required => false, class: "form-control" %>
    </div>
    <div class="col-sm-7">
    </div>
</div>
<div class="form-group">
  <%= f.label :translated_text, (t :translated_text), class: 'col-sm-2 control-label' %>
    <div class="col-sm-3">
      <%= f.input_field :translated_text, as: :string, :required => false, class: "form-control" %>
    </div>
        <div class="col-sm-7">
    </div>
</div>
<div class="form-group">
  <%= f.label :review_date, (t :review_date), class: 'col-sm-2 control-label' %>
    <div class="col-sm-3">
      <%= f.input_field :review_date, as: :string, value: (Time.now).strftime('%d/%m/%Y'), class: "form-control"  %>
  </div>
      <div class="col-sm-7">
    </div>
</div>

app/views/cards/edit.html.erb
<h2> <%= t :edit_card_title %></h2>
<div class="form-horizontal">
<%= simple_form_for @card do |f| %>
<%= render partial: "form", locals: { f: f } %>
<%= f.hidden_field :user_id, value: current_user.id %>
<%= f.file_field :avatar %>
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
<%= f.button :submit, (t :edit_confirm), class: "btn btn-info btn-sm" %>
</div>
</div>
<% end %>
</div>

app/views/cards/index.html.erb
<h2>
  <%= t :all_cards %>
</h2>

<table class="table table-bordered">
  <tr class="info">
    <th><%= t :original_text %></th>
    <th><%= t :translated_text %></th>
    <th><%= t :review_date %></th>
    <th><%= t :deck %></th>
    <th><%= t :action %></th>
  </tr>

  <% @cards.each do |card| %>
    <tr>
      <td><%= card.original_text %></td>
      <td><%= card.translated_text %></td>
      <td><%= card.review_date.strftime('%d/%m/%Y') %></td>
      <td><%= card.deck_id %></td>
      <td><%= link_to (t :show), card_path(card), class: "btn btn-info btn-xs" %>
        <%= link_to (t :edit), edit_card_path(card), class: "btn btn-info btn-xs" %>
        <%= link_to (t :del_card), card_path(card), method: :delete, data: { confirm: (t :del_confirm) }, class: "btn btn-info btn-xs" %></td>
    </tr>
  <% end %>
</table>

app/views/cards/new.html.erb
<h2> <%= t :new_card_title %></h2>

<% unless @decks.exists? %>
<h3> <%= t :alert_card %>! </h3>
<% else %>
<h3> <%= t :check_translate_title %></h3>
<div class="form-horizontal">
<%= simple_form_for @card do |f| %>
<%= render partial: "form", locals: { f: f } %>
<%= f.hidden_field :user_id, value: current_user.id %>
<%= f.file_field :avatar %>
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
<%= f.button :submit, (t :new_card_title), class: "btn btn-info btn-sm" %>
</div>
</div>
<% end %>
</div>
<% end %>

app/views/cards/show.html.erb
<h2><%= t :show_card_title %></h2>
<p><%= t :original_text %>: <%= @card.original_text %></p>
<p><%= t :translated_text %>: <%= @card.translated_text %></p>
<p><%= t :review_date %>: <%= @card.review_date %></p>