config/routes.rb
Rails.application.routes.draw do
  get 'oauths/oauth'

  get 'oauths/callback'

  root "home#index"

  resources :cards
  post "check_card" => "home#check_card"
  resources :users
  resources :user_sessions

  resources :decks do
    member do
      post :activate
    end
  end

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback" # for use with Github, Facebook
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

end

app/models/deck.rb
class Deck < ActiveRecord::Base
  has_many :cards, dependent: :destroy
  belongs_to :user
  validates :description, presence: true

  def self.find_active_deck
    find_by(active: true)
  end
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  before_action :find_deck, only: [:show, :edit, :update, :destroy, :activate, :deactivate]
  before_action :change_status_to_false, only: [:activate]
  def index
    @decks = current_user.decks
  end

  def show
  end

  def new
    @deck = Deck.new
  end

  def create
    @deck = Deck.create(get_deck_params)

    if @deck.save
      redirect_to decks_path
    else
      render "new"
    end
  end

  def edit
  end

  def update
    @deck.update_attributes(get_deck_params)

    if @deck.errors.empty?
      redirect_to @deck
    else
      render "edit"
    end
  end

  def destroy
    @deck.destroy
    redirect_to decks_path
  end

  def activate
    @deck.active ? @deck.update(active: false) : @deck.update(active: true)
    redirect_to decks_path
  end

  private

  def get_deck_params
    params.require(:deck).permit(:description, :active, :user_id)
  end

  def find_deck
    @deck = Deck.find(params[:id])
  end

  def change_status_to_false
    active_deck = current_user.decks.find_active_deck
    active_deck.update(active: false) unless active_deck.nil?
  end
end

app/views/decks/_form.html.erb
<div class="form-group">
  <%= f.label :description, (t :deck_description), class: 'col-sm-2 control-label' %>
    <div class="col-sm-3">
      <%= f.input_field :description, as: :string, :required => false, class: "form-control" %>
    </div>
    <div class="col-sm-7">
    </div>
</div>

app/views/decks/edit.html.erb
<h2><%= t :edit_deck_title %></h2>

<div class="form-horizontal">
<%= simple_form_for @deck do |f| %>
<%= render partial: "form", locals: { f: f } %>
<%= f.hidden_field :user_id, value: current_user.id %>
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
<%= f.button :submit, (t :edit_confirm), class: "btn btn-info btn-sm" %>
<%= link_to (t :change_active_status), activate_deck_path(@deck), method: :post, data: { confirm: (t :del_confirm) }, class: "btn btn-info btn-sm" %>
</div>
</div>
<% end %>
</div>

app/views/decks/index.html.erb
<h2>
  <%= t :all_decks %>
</h2>

<table class="table table-bordered">
  <tr class="info">
    <th><%= t :deck_description %></th>
    <th><%= t :active_status %></th>
    <th><%= t :action %></th>
  </tr>

  <% @decks.each do |deck| %>
    <tr>
      <td><%= deck.description %></td>
      <td><%= deck.active %></td>
      <td><%= link_to (t :show), deck_path(deck), class: "btn btn-info btn-xs" %>
        <%= link_to (t :edit), edit_deck_path(deck), class: "btn btn-info btn-xs" %>
        <%= link_to (t :del_deck), deck_path(deck), method: :delete, data: { confirm: (t :del_confirm) }, class: "btn btn-info btn-xs" %></td>
    </tr>
  <% end %>
</table>

app/views/decks/new.html.erb
<h2> <%= t :new_deck_title %></h2>
<div class="form-horizontal">
<%= simple_form_for @deck do |f| %>
<%= render partial: "form", locals: { f: f } %>
<%= f.hidden_field :active, value: false %>
<%= f.hidden_field :user_id, value: current_user.id %>
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
<%= f.button :submit, (t :new_deck_title), class: "btn btn-info btn-sm" %>
</div>
</div>
<% end %>
</div>

app/views/decks/show.html.erb
<h2><%= t :deck %></h2>
<p><%= t :deck_description %>: <%= @deck.description %></p>
<p><%= t :active_status %>?: <%= @deck.active %></p>