config/routes.rb
Rails.application.routes.draw do
  get 'oauths/oauth'

  get 'oauths/callback'

  root "home#index"

  resources :cards
  post "check_card" => "home#check_card"
  resources :users
  resources :user_sessions

  resources :decks do
    member do
      post :activate
    end
  end

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback" # for use with Github, Facebook
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= t :flashcards %></title>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="container">
  <header class="row">
    <div class="col-md-8">
      <h1><%= t :flashcards %></h1>
    </div>
    <div class="col-md-2">
      <% I18n.available_locales.map do |locale| %>
      <%= link_to locale, locale: locale  %>
      <% end %>
    </div>
    <div id="nav" class="col-md-2">
    <% if current_user %>
      <%= link_to (t :profile), edit_user_path(current_user.id), class: "btn btn-info btn-xs"  %>
      <%= link_to (t :sign_out), :logout, method: :post, class: "btn btn-info btn-xs"  %>
    <% else %>
      <%= link_to (t :sign_up), new_user_path, class: "btn btn-info btn-xs"  %> |
      <%= link_to (t :sign_in), :login, class: "btn btn-info btn-xs"  %>
      <%= link_to 'Twitter', auth_at_provider_path(:provider => :twitter) %>
    <% end %>
  </div>
  <div>
    <p id="notice"><%= flash[:notice] %></p>
    <p id="alert"><%= flash[:alert] %></p>
  </div>
  </header>
  <% if current_user %>
    <nav class="row">
      <div class="col-md-12">
        <ul class="list-unstyled list-inline">
          <li><%= link_to (t :all_cards), cards_path, class: "btn btn-info" %></li>
          <li><%= link_to (t :add_card), new_card_path, class: "btn btn-info" %></li>
          <li><%= link_to (t :all_decks), decks_path, class: "btn btn-info" %></li>
          <li><%= link_to (t :add_deck), new_deck_path, class: "btn btn-info" %></li>
        </ul>
      </div>
    </nav>
  <% end %>
  <section class="row">
    <div class="col-md-12">
     <% flash.each do |key, value| %>
        <%= value %>
      <% end %>
    <%= yield %>
    </div>
  </section>
</body>
</html>